# Process ID
spring.pid.file=${user.home}/apps/seesaw/seesaw-web/${spring.application.name}.pid

# DataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.0.0.69:5432/seesaw
spring.datasource.username=seesaw_admin
spring.datasource.password=1234

# JPA
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Logging
logging.level.root=info
logging.level.org.springframework.web=info
logging.level.org.springframework.security=debug
logging.level.org.springframework.orm.jpa=info
logging.level.org.hibernate.sql=info
logging.level.org.hibernate.orm.jdbc.bind=info
