# suppress inspection "SpringBootApplicationProperties" for whole file

server.address=0.0.0.0
server.port=8080

# Import
spring.config.import=optional:classpath:/datasource-${spring.profiles.active}.properties,optional:classpath:/application.properties

# JPA
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Logging
logging.level.root=info
logging.level.org.springframework.web=info
logging.level.org.springframework.security=debug
logging.level.org.springframework.orm.jpa=info
logging.level.org.hibernate.sql=info
logging.level.org.hibernate.orm.jdbc.bind=info

# \uCCA8\uBD80\uD30C\uC77C
kr.me.seesaw.filepath=YOUR_PATH

# OAuth
spring.security.oauth2.client.registration.naver.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.naver.client-secret=YOUR_CLIENT_SECRET
spring.security.oauth2.client.registration.naver.redirect-uri=YOUR_REDIRECT_URI
spring.security.oauth2.client.registration.naver.authorization-grant-type=YOUR_AUTHORIZATION_GRANT_TYPE
spring.security.oauth2.client.registration.naver.scope=YOUR_SCOPE
spring.security.oauth2.client.registration.naver.client-name=YOUR_CLIENT_NAME

spring.security.oauth2.client.provider.naver.authorization-uri=YOUR_AUTHORIZATION_URI
spring.security.oauth2.client.provider.naver.token-uri=YOUR_TOKEN_URI
spring.security.oauth2.client.provider.naver.user-info-uri=YOUR_USER_INFO_URI
spring.security.oauth2.client.provider.naver.user-name-attribute=YOUR_USER_NAME_ATTRIBUTE
