# suppress inspection "SpringBootApplicationProperties" for whole file

# Import
spring.config.import=optional:classpath:/datasource-prod.properties,optional:classpath:/application.properties

# JPA
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Logging
logging.level.root=info
logging.level.org.springframework.web=info
logging.level.org.springframework.security=debug
logging.level.org.springframework.orm.jpa=info
logging.level.org.hibernate.sql=info
logging.level.org.hibernate.orm.jdbc.bind=info
