spring.application.name=seesaw-web
spring.application.version=0.0.1-SNAPSHOT
server.address=localhost
server.port=8080

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;
spring.datasource.url=jdbc:h2:file:./testdb;MODE=PostgreSQL;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=tester
spring.datasource.password=tester

# JPA
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Lazy initialization
spring.main.lazy-initialization=true

# Cache
spring.cache.type=hazelcast

# Actuator
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.version=${spring.application.version}
info.app.profiles=${spring.profiles.active:default}

# Logging
spring.output.ansi.enabled=always
logging.level.root=info
logging.level.org.springframework.web=debug
logging.level.org.springframework.security=debug
logging.level.org.springframework.orm.jpa=debug

# Hibernate SQL \uB85C\uADF8 \uCD9C\uB825 \uBC0F \uBC14\uC778\uB529 \uAC12 \uD45C\uC2DC, \uBD88\uD544\uC694\uD55C \uCD94\uCD9C \uB85C\uADF8 \uBE44\uD65C\uC131\uD654
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.orm.jdbc.extract=off


# \uC815\uC801 \uC790\uC6D0 \uACBD\uB85C
spring.web.resources.static-locations=classpath:/static/, classpath:/node_modules/

# HTML \uBE44\uD45C\uC900 HTTP method(ex - PUT, DELETE ..)\uB97C \uD65C\uC131\uD654 \uD569\uB2C8\uB2E4.
spring.mvc.hiddenmethod.filter.enabled=true

# Thymeleaf template engine cache\uB97C \uBE44\uD65C\uC131\uD654\uD569\uB2C8\uB2E4. \uD15C\uD50C\uB9BF \uD30C\uC77C \uBCC0\uACBD \uC0AC\uD56D\uC774 \uC989\uC2DC \uBC18\uC601\uB429\uB2C8\uB2E4.
spring.thymeleaf.cache=false

# \uC6F9 \uB9AC\uC18C\uC2A4(image, CSS, JS \uD30C\uC77C \uB4F1)\uC758 \uCE90\uC2DC \uB9CC\uB8CC \uC2DC\uAC04\uC744 \uCD08\uB2E8\uC704\uB85C \uC124\uC815\uD569\uB2C8\uB2E4.
spring.web.resources.cache.period=5

# \uBA54\uC2DC\uC9C0 \uD30C\uC77C(i18n \uC9C0\uC6D0 \uD30C\uC77C)\uC758 \uCE90\uC2DC \uB9CC\uB8CC \uC2DC\uAC04\uC744 \uCD08 \uB2E8\uC704\uB85C \uC124\uC815\uD569\uB2C8\uB2E4. \uBA54\uC2DC\uC9C0 \uBCC0\uACBD \uC0AC\uD56D\uC774 \uC989\uC2DC \uBC18\uC601\uB429\uB2C8\uB2E4.
spring.messages.cache-duration=5

spring.data.rest.base-path=/rest-api

# \uCCA8\uBD80\uD30C\uC77C
kr.me.seesaw.filepath=${user.home}/seesaw/files
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB
