spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/seesaw?currentSchema=public
spring.datasource.username=seesaw_admin
spring.datasource.password=1234